version: 2
jobs:
  build:
    working_directory: ~/gymnastjs/gymnast
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      TARGET_URL: https://gymnastjs.github.io/gymnast/branch/$CIRCLE_BRANCH
    docker:
      - image: circleci/node:10.9.0-jessie
        command: /sbin/init
    steps:
      - checkout
      # Test
      - run: scripts/citests.sh
      # Deployment
      - type: deploy
        name: 'Publish to npm'
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ];
            then ./scripts/deploynpm.sh;
          fi
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: test/screenshot/images
      - store_artifacts:
          path: /tmp/circleci-test-results
